name: HypixelSkyblock
version: 0.1
author: SimplyAmazing
main: org.hypixelskyblockrecreation.simplyamazing.Main
description: An attempt at a Hypixel SkyBlock recreation.

commands:
   coins:
      description: Commands related to coins!
   item:
      aliases: [i]
      description: Get a SkyBlock item!
   material:
      aliases: [m]
      description: Get a SkyBlock material!
   sbgiveall:
      aliases: [giveall]
      description: Give yourself every SkyBlock item!
   sbskills:
      description: Commands related to skills!
   skilltest:
      description: Test command!
   skyblockmenu:
      aliases: [sbm]
      description: Opens the SkyBlock menu!